services:
  app:
    container_name: server_app
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - PORT=3000
      - MIN_OPT=-1
      - MAX_OPT=11
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    container_name: redis_server
    image: "redis:alpine"
    ports:
      - "6379:6379"